[tool.vercel]
entrypoint = "main.py"

app = 'bot-rfbb'
primary_region = 'iad'

[build]

[[restart]]
  policy = "always"

[processes]
  app = "python bot.py"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
